# Generated by Django 5.2.4 on 2025-07-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
