# Generated by Django 5.2.4 on 2025-08-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tourpackage_booking_traveler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='includes',
            field=models.TextField(default='Hotel, food, sightseeing'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(upload_to='tour_images/'),
        ),
    ]
