# Generated by Django 5.2.4 on 2025-08-07 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_amount_tourpackage_price_tourpackage_includes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('seats_available', models.PositiveIntegerField(default=30)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='core.tourpackage')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('tour', 'date')},
            },
        ),
    ]
