# Generated by Django 5.2.4 on 2025-10-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
