# Generated by Django 5.2.8 on 2026-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_customuser_profile_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourpackage",
            name="image",
            field=models.URLField(max_length=500),
        ),
    ]
